### ISSUE TITLE
[BUG] RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by hirbod** [Luehang/react-native-camera-roll-selector#1]
As soon as I implement your lib (latest version, installed right now) using your provided example, I get a RangeError: Maximum call stack size exceeded. The error is located in MasonryList at src/index.js:205

**Comment by Luehang** [comment]
Hi, there has been some major updates and improvement.  Update to latest.  Thanks.

```bash
$ npm install --save react-native-camera-roll-selector@latest
```

or

```bash
$ yarn add react-native-camera-roll-selector@latest
```
